-- User identity and encrypted state. UUIDs are generated by the application.
CREATE TABLE users (
    id UUID PRIMARY KEY,
    max_id_lookup BYTEA NOT NULL UNIQUE CHECK (octet_length(max_id_lookup) = 32),
    lookup_key_version INTEGER NOT NULL CHECK (lookup_key_version > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_state (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    profile_ciphertext BYTEA,
    profile_algorithm_version SMALLINT,
    profile_key_version INTEGER,
    profile_revision BIGINT NOT NULL DEFAULT 0,
    draft_ciphertext BYTEA,
    draft_algorithm_version SMALLINT,
    draft_key_version INTEGER,
    draft_revision BIGINT NOT NULL DEFAULT 0,
    favorites_ciphertext BYTEA,
    favorites_algorithm_version SMALLINT,
    favorites_key_version INTEGER,
    favorites_revision BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT profile_envelope_consistent CHECK (
        (profile_ciphertext IS NULL AND profile_algorithm_version IS NULL AND profile_key_version IS NULL AND profile_revision = 0)
        OR (profile_ciphertext IS NOT NULL AND octet_length(profile_ciphertext) >= 28 AND profile_algorithm_version IS NOT NULL AND profile_algorithm_version > 0 AND profile_key_version IS NOT NULL AND profile_key_version > 0 AND profile_revision > 0)
    ),
    CONSTRAINT draft_envelope_consistent CHECK (
        (draft_ciphertext IS NULL AND draft_algorithm_version IS NULL AND draft_key_version IS NULL AND draft_revision = 0)
        OR (draft_ciphertext IS NOT NULL AND octet_length(draft_ciphertext) >= 28 AND draft_algorithm_version IS NOT NULL AND draft_algorithm_version > 0 AND draft_key_version IS NOT NULL AND draft_key_version > 0 AND draft_revision > 0)
    ),
    CONSTRAINT favorites_envelope_consistent CHECK (
        (favorites_ciphertext IS NULL AND favorites_algorithm_version IS NULL AND favorites_key_version IS NULL AND favorites_revision = 0)
        OR (favorites_ciphertext IS NOT NULL AND octet_length(favorites_ciphertext) >= 28 AND favorites_algorithm_version IS NOT NULL AND favorites_algorithm_version > 0 AND favorites_key_version IS NOT NULL AND favorites_key_version > 0 AND favorites_revision > 0)
    )
);

CREATE TABLE sessions (
    token_hash BYTEA PRIMARY KEY CHECK (octet_length(token_hash) = 32),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT session_expiry_after_creation CHECK (expires_at > created_at)
);
CREATE INDEX sessions_user_id_idx ON sessions(user_id);
CREATE INDEX sessions_expires_at_idx ON sessions(expires_at);

CREATE TABLE questionnaire_versions (
    version TEXT PRIMARY KEY,
    bank_sha256 BYTEA NOT NULL CHECK (octet_length(bank_sha256) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
